### ISSUE TITLE
 java.security.InvalidKeyException: Failed to unwrap key

### ISSUE THREAD

**Issue by rostyslavroshak** [BottleRocketApps/Android-Vault#13]
Hello, I had the crash once on OnePlusOne 5T Android 8.1:

```
E/AndroidKeystoreTester: Caught an exception while creating the AndroidKeystoreSecretKeyWrapper
    java.security.InvalidKeyException: Failed to unwrap key
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:682)
        at javax.crypto.Cipher.unwrap(Cipher.java:2126)
        at com.bottlerocketstudios.vault.keys.wrapper.AbstractAndroidKeystoreSecretKeyWrapper.unwrap(AbstractAndroidKeystoreSecretKeyWrapper.java:151)
        at com.bottlerocketstudios.vault.keys.wrapper.AbstractAndroidKeystoreSecretKeyWrapper.testKey(AbstractAndroidKeystoreSecretKeyWrapper.java:169)
        at com.bottlerocketstudios.vault.keys.storage.hardware.AndroidKeystoreTester.performAndroidKeystoreTest(AndroidKeystoreTester.java:63)
        at com.bottlerocketstudios.vault.keys.storage.hardware.AndroidKeystoreTester.canUseAndroidKeystore(AndroidKeystoreTester.java:51)
        at com.bottlerocketstudios.vault.keys.storage.CompatSharedPrefKeyStorageFactory.canUseAndroidKeystore(CompatSharedPrefKeyStorageFactory.java:131)
        at com.bottlerocketstudios.vault.keys.storage.CompatSharedPrefKeyStorageFactory.determineBestSupportedWrapperType(CompatSharedPrefKeyStorageFactory.java:121)
        at com.bottlerocketstudios.vault.keys.storage.CompatSharedPrefKeyStorageFactory.createKeyStorage(CompatSharedPrefKeyStorageFactory.java:68)
        at com.bottlerocketstudios.vault.SharedPreferenceVaultFactory.getCompatAes256Vault(SharedPreferenceVaultFactory.java:67)
        at com.bottlerocketstudios.vault.SharedPreferenceVaultFactory.getAppKeyedCompatAes256Vault(SharedPreferenceVaultFactory.java:94)
        at com.bottlerocketstudios.vault.SharedPreferenceVaultFactory.getAppKeyedCompatAes256Vault(SharedPreferenceVaultFactory.java:105)
```

**Comment by sandeeptengale** [comment]
Any solution for this??
I have to replace the whole library because of this one issue

**Comment by rogerhu** [comment]
Did you update to latest (v1.4.2)?  There was a bug in Android O/P keystore..
