### ISSUE TITLE
Android P - KeyStore exception android.os.ServiceSpecificException

### ISSUE THREAD

**Issue by krasavello13** [BottleRocketApps/Android-Vault#15]
KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1956)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
        at java.security.KeyStore.getEntry(KeyStore.java:1560)
        at com.bottlerocketstudios.vault.keys.wrapper.AbstractAndroidKeystoreSecretKeyWrapper.getKeyPair(AbstractAndroidKeystoreSecretKeyWrapper.java:82)
        at com.bottlerocketstudios.vault.keys.wrapper.AbstractAndroidKeystoreSecretKeyWrapper.unwrap(AbstractAndroidKeystoreSecretKeyWrapper.java:167)
        at com.bottlerocketstudios.vault.keys.storage.SharedPrefKeyStorage.loadSecretKey(SharedPrefKeyStorage.java:113)
        at com.bottlerocketstudios.vault.keys.storage.SharedPrefKeyStorage.loadKey(SharedPrefKeyStorage.java:60)
        at com.bottlerocketstudios.vault.keys.storage.SharedPrefKeyStorage.hasKey(SharedPrefKeyStorage.java:147)
        at com.bottlerocketstudios.vault.StandardSharedPreferenceVault.isKeyAvailable(StandardSharedPreferenceVault.java:336)
        at com.bottlerocketstudios.vault.SharedPreferenceVaultFactory.getAppKeyedCompatAes256Vault(SharedPreferenceVaultFactory.java:95)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by rogerhu** [comment]
Looks related here: https://stackoverflow.com/a/53287084/961939

**Comment by rogerhu** [comment]
https://github.com/BottleRocketStudios/Android-Vault/blob/master/AndroidVault/vault/src/main/java/com/bottlerocketstudios/vault/keys/wrapper/AbstractAndroidKeystoreSecretKeyWrapper.java#L82

**Comment by rogerhu** [comment]
See: https://github.com/BottleRocketStudios/Android-Vault/pull/18
